sudo: required
dist: trusty
language: node_js
node_js:
  - node

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
services:
  - postgresql

before_script:
  - psql -c 'drop database if exists docMan-test;' -U postgres
  - psql -c 'create database docMan-test;' -U postgres
  - NODE_ENV=test npm run migration

after_success:
  - npm run coverage
  - npm run coveralls
addons:
  postgresql: "9.3"

after_failure:
  - npm run coverage
  - npm run coveralls
